### ISSUE TITLE
Can't buy anything because of this error

### ISSUE THREAD

**Issue by amsator** [prospectors/public#10]
![Screenshot_13](https://user-images.githubusercontent.com/36524018/62228230-ed240200-b3c5-11e9-9b56-d448dd44e777.png)

**Comment by canab** [comment]
There is a limit on purchased stuffs which are still stored on their locations. You have to transfer at least one of them, then it will be possible to purchase another one.

**Comment by amsator** [comment]
Thank you, dont know this
