### ISSUE TITLE
sales 

### ISSUE THREAD

**Issue by salvadoreanking** [prospectors/public#16]
Every time I sell a percent of my earnings disappear, is not always the same amount so I assume is sales tax it didn't happen before but with the updates you never know, I just want to make sure if it is a new implementation or is just a bug, can you please clarify it for me and if is a bug can you help me with that please? 
thank you very much I will be waiting for your response.

**Comment by canab** [comment]
There always was 5% tax for money user earned by sell on market and by doing orders (now also for land auctions).
<img width="406" alt="Screen Shot 2019-08-10 at 23 21 32" src="https://user-images.githubusercontent.com/275162/62826524-c89a0800-bbc5-11e9-882e-85f961b08231.png">
