### ISSUE TITLE
multiple stuff in ALL MY STUFF screen 

### ISSUE THREAD

**Issue by salvadoreanking** [prospectors/public#17]
When I open all my stuff in the menu the screen show my stuff multiple times not one or two but many more times, here is a screenshot so you can see what I'm talking about, thank you and I hope you can help me 
![Screenshot (192)](https://user-images.githubusercontent.com/50181886/62848959-8b4f7c00-bc92-11e9-9318-aa5826926aeb.png)

**Comment by viewphoria6** [comment]
Ive also experienced this with resouces and tools

**Comment by canab** [comment]
fixed for the next release
