### ISSUE TITLE
Auction listing fee.

### ISSUE THREAD

**Issue by pepperoniss** [prospectors/public#18]
I suggest introducing a fee, e.g. 0.5% - 1% of the starting price for listing the auction. This should increase the number of transactions and the starting prices would become more marketable.

**Comment by mmelkiy** [comment]
Reflecting on this proposal, the team decided that it would be unfair to the players, because everyone wants to get as much as possible for their plot - this result can be obtained only in an experimental way, which in turn will lead to multiple fees losses.
