### ISSUE TITLE
Building: "finish" shows wrong number of worker slots

### ISSUE THREAD

**Issue by GassaFM** [prospectors/public#4]
When a building is being built, we can click various stages to see information about these stages.
Here, the "Finish" stage says that the number of worker slots in a producing building will be 3.
![image](https://user-images.githubusercontent.com/2153020/60463614-25181800-9c55-11e9-8803-09d14c76f3f4.png)
The number is wrong: the Academy page shows that it is 10, not 3.

**Comment by canab** [comment]
deployed
