### ISSUE TITLE
UI: buttons "take on" and "take off" appear simultaneously

### ISSUE THREAD

**Issue by GassaFM** [prospectors/public#6]
When you click the second tool in the backpack right after taking the first tool, both "take on" and "take off" action buttons appear.
![image](https://user-images.githubusercontent.com/2153020/60509566-eb3b2600-9cd5-11e9-8171-1f0b6f7f5094.png)

**Comment by canab** [comment]
@andriyha reproduced, you have to select backpack item quickly - before refresh event from the action fires
